import type { NextPage } from 'next';
import Head from 'next/head';
import { getRequest } from 'services/utils';

const Home: NextPage = () => {
  const handleClick = async () => {
    try {
      const res = await getRequest('addresses');
      console.log(res);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <div>
      <Head>
        <title>Merchadise Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello, Merchadise Test</h1>
      <button type="button" onClick={handleClick}>
        Test
      </button>
    </div>
  );
};

export default Home;
